version: '3.9'

volumes:
  db_data: {}
  redis_data: {}

networks:
  default:
    external:
      name: hongaeting-v3-net

services:
  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    container_name: redis
    image: redis
    volumes:
      - ./redis:/var/lib/redis
    ports:
      - ${REDIS_PORT}:6379

  backend:
    container_name: backend
    build:
      context: .
    ports:
      - 4000:${API_PORT}
    links:
      - db
    depends_on:
      - db
    restart: always
    command:
      - bash
      - -c
      - |
        /wait-for-it.sh db:3306 -t 10
        pm2-docker /dist/main.js
