version: '3.9'

volumes:
  db_dev: {}

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes: 
      - db_dev:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
